/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quantum.mutex.util;


/**
 *
 * @author Florent
 */

public enum SupportedRegularMimeType {
    
    APPLICATION_JAVA_VM("application/java-vm"),
    AUDIO_X_WAV("audio/x-wav"),
    AUDIO_X_AIFF("audio/x-aiff"),
    AUDIO_BASIC("audio/basic"),
    APPLICATION_X_MIDI("application/x-midi"),
    AUDIO_MIDI("audio/midi"),
    APPLICATION_VND_MS_HTMLHELP("application/vnd.ms-htmlhelp"),
    APPLICATION_CHM("application/chm"),
    APPLICATION_X_CHM("application/x-chm"),
    TEXT_X_JAVA_SOURCE("text/x-java-source"),
    TEXT_X_C_SRC("text/x-c++src"),
    TEXT_X_GROOVY("text/x-groovy"),
    APPLICATION_PKCS7_SIGNATURE("application/pkcs7-signature"),
    APPLICATION_PKCS7_MIME("application/pkcs7-mime"),
    IMAGE_VND_DWG("image/vnd.dwg"),
    APPLICATION_X_IBOOKS_ZIP("application/x-ibooks+zip"),
    APPLICATION_EPUB_ZIP("application/epub+zip"),
    APPLICATION_X_ELF("application/x-elf"),
    APPLICATION_X_SHAREDLIB("application/x-sharedlib"),
    APPLICATION_X_EXECUTABLE("application/x-executable"),
    APPLICATION_X_MSDOWNLOAD("application/x-msdownload"),
    APPLICATION_X_COREDUMP("application/x-coredump"),
    APPLICATION_X_OBJECT("application/x-object"),
    APPLICATION_ATOM_XML("application/atom+xml"),
    APPLICATION_RSS_XML("application/rss+xml"),
    APPLICATION_X_FONT_ADOBE_METRIC("application/x-font-adobe-metric"),
    APPLICATION_X_FONT_TTF("application/x-font-ttf"),
    APPLICATION_X_HDF("application/x-hdf"),
    APPLICATION_X_ASP("application/x-asp"),
    APPLICATION_XHTML_XML("application/xhtml+xml"),
    APPLICATION_VND_WAP_XHTML_XML("application/vnd.wap.xhtml+xml"),
    TEXT_HTML("text/html"),
    IMAGE_X_MS_BMP("image/x-ms-bmp"),
    IMAGE_PNG("image/png"),
    IMAGE_X_ICON("image/x-icon"),
    IMAGE_VND_WAP_WBMP("image/vnd.wap.wbmp"),
    IMAGE_GIF("image/gif"),
    IMAGE_BMP("image/bmp"),
    IMAGE_X_XCF("image/x-xcf"),
    IMAGE_VND_ADOBE_PHOTOSHOP("image/vnd.adobe.photoshop"),
    IMAGE_TIFF("image/tiff"),
    TEXT_VND_IPTC_ANPA("text/vnd.iptc.anpa"),
    APPLICATION_VND_APPLE_IWORK("application/vnd.apple.iwork"),
    APPLICATION_VND_APPLE_NUMBERS("application/vnd.apple.numbers"),
    APPLICATION_VND_APPLE_KEYNOTE("application/vnd.apple.keynote"),
    APPLICATION_VND_APPLE_PAGES("application/vnd.apple.pages"),
    IMAGE_JPEG("image/jpeg"),
    MESSAGE_RFC822("message/rfc822"),
    APPLICATION_X_MATLAB_DATA("application/x-matlab-data"),
    APPLICATION_MBOX("application/mbox"),
    APPLICATION_VND_MS_OUTLOOK_PST("application/vnd.ms-outlook-pst"),
    APPLICATION_X_MSPUBLISHER("application/x-mspublisher"),
    APPLICATION_X_TIKA_MSOFFICE("application/x-tika-msoffice"),
    APPLICATION_VND_MS_EXCEL("application/vnd.ms-excel"),
    APPLICATION_SLDWORKS("application/sldworks"),
    APPLICATION_X_TIKA_MSWORKS_SPREADSHEET("application/x-tika-msworks-spreadsheet"),
    APPLICATION_VND_MS_POWERPOINT("application/vnd.ms-powerpoint"),
    APPLICATION_X_TIKA_MSOFFICE_EMBEDDED_FORMAT_OLE10_NATIVE("application/x-tika-msoffice-embedded; format=ole10_native"),
    APPLICATION_VND_MS_PROJECT("application/vnd.ms-project"),
    APPLICATION_X_TIKA_OOXML_PROTECTED("application/x-tika-ooxml-protected"),
    APPLICATION_MSWORD("application/msword"),
    APPLICATION_VND_MS_OUTLOOK("application/vnd.ms-outlook"),
    APPLICATION_VND_VISIO("application/vnd.visio"),
    APPLICATION_X_TNEF("application/x-tnef"),
    APPLICATION_MS_TNEF("application/ms-tnef"),
    APPLICATION_VND_MS_TNEF("application/vnd.ms-tnef"),
    APPLICATION_VND_MS_EXCEL_SHEET_MACROENABLED_12("application/vnd.ms-excel.sheet.macroenabled.12"),
    APPLICATION_VND_MS_POWERPOINT_PRESENTATION_MACROENABLED_12("application/vnd.ms-powerpoint.presentation.macroenabled.12"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_TEMPLATE("application/vnd.openxmlformats-officedocument.spreadsheetml.template"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_TEMPLATE("application/vnd.openxmlformats-officedocument.presentationml.template"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
    APPLICATION_VND_MS_EXCEL_ADDIN_MACROENABLED_12("application/vnd.ms-excel.addin.macroenabled.12"),
    APPLICATION_VND_MS_WORD_DOCUMENT_MACROENABLED_12("application/vnd.ms-word.document.macroenabled.12"),
    APPLICATION_VND_MS_EXCEL_TEMPLATE_MACROENABLED_12("application/vnd.ms-excel.template.macroenabled.12"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_TEMPLATE("application/vnd.openxmlformats-officedocument.wordprocessingml.template"),
    APPLICATION_VND_MS_POWERPOINT_SLIDESHOW_MACROENABLED_12("application/vnd.ms-powerpoint.slideshow.macroenabled.12"),
    APPLICATION_VND_MS_POWERPOINT_ADDIN_MACROENABLED_12("application/vnd.ms-powerpoint.addin.macroenabled.12"),
    APPLICATION_VND_MS_WORD_TEMPLATE_MACROENABLED_12("application/vnd.ms-word.template.macroenabled.12"),
    APPLICATION_X_TIKA_OOXML("application/x-tika-ooxml"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_SLIDESHOW("application/vnd.openxmlformats-officedocument.presentationml.slideshow"),
    AUDIO_MPEG("audio/mpeg"),
    VIDEO_3GPP2("video/3gpp2"),
    VIDEO_MP4("video/mp4"),
    VIDEO_QUICKTIME("video/quicktime"),
    AUDIO_MP4("audio/mp4"),
    APPLICATION_MP4("application/mp4"),
    VIDEO_X_M4V("video/x-m4v"),
    VIDEO_3GPP("video/3gpp"),
    APPLICATION_X_NETCDF("application/x-netcdf"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_GRAPHICS_TEMPLATE("application/x-vnd.oasis.opendocument.graphics-template"),
    APPLICATION_VND_SUN_XML_WRITER("application/vnd.sun.xml.writer"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_TEXT("application/x-vnd.oasis.opendocument.text"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_TEXT_WEB("application/x-vnd.oasis.opendocument.text-web"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_SPREADSHEET_TEMPLATE("application/x-vnd.oasis.opendocument.spreadsheet-template"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_FORMULA_TEMPLATE("application/vnd.oasis.opendocument.formula-template"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION("application/vnd.oasis.opendocument.presentation"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_IMAGE_TEMPLATE("application/vnd.oasis.opendocument.image-template"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_GRAPHICS("application/x-vnd.oasis.opendocument.graphics"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_CHART_TEMPLATE("application/vnd.oasis.opendocument.chart-template"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION_TEMPLATE("application/vnd.oasis.opendocument.presentation-template"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_IMAGE_TEMPLATE("application/x-vnd.oasis.opendocument.image-template"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_FORMULA("application/vnd.oasis.opendocument.formula"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_IMAGE("application/x-vnd.oasis.opendocument.image"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET_TEMPLATE("application/vnd.oasis.opendocument.spreadsheet-template"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_CHART_TEMPLATE("application/x-vnd.oasis.opendocument.chart-template"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_FORMULA("application/x-vnd.oasis.opendocument.formula"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET("application/vnd.oasis.opendocument.spreadsheet"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT_WEB("application/vnd.oasis.opendocument.text-web"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT_TEMPLATE("application/vnd.oasis.opendocument.text-template"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT("application/vnd.oasis.opendocument.text"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_FORMULA_TEMPLATE("application/x-vnd.oasis.opendocument.formula-template"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_SPREADSHEET("application/x-vnd.oasis.opendocument.spreadsheet"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_CHART("application/x-vnd.oasis.opendocument.chart"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT_MASTER("application/vnd.oasis.opendocument.text-master"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_TEXT_MASTER("application/x-vnd.oasis.opendocument.text-master"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_TEXT_TEMPLATE("application/x-vnd.oasis.opendocument.text-template"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_GRAPHICS("application/vnd.oasis.opendocument.graphics"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_GRAPHICS_TEMPLATE("application/vnd.oasis.opendocument.graphics-template"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_PRESENTATION("application/x-vnd.oasis.opendocument.presentation"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_IMAGE("application/vnd.oasis.opendocument.image"),
    APPLICATION_X_VND_OASIS_OPENDOCUMENT_PRESENTATION_TEMPLATE("application/x-vnd.oasis.opendocument.presentation-template"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_CHART("application/vnd.oasis.opendocument.chart"),
    APPLICATION_PDF("application/pdf"),
    APPLICATION_RTF("application/rtf"),
    TEXT_PLAIN("text/plain"),
    VIDEO_X_FLV("video/x-flv"),
    APPLICATION_XML("application/xml"),
    IMAGE_SVG_XML("image/svg+xml"),
    APPLICATION_X_FICTIONBOOK_XML("application/x-fictionbook+xml"),
    AUDIO_X_OGGFLAC("audio/x-oggflac"),
    AUDIO_X_FLAC("audio/x-flac"),
    APPLICATION_KATE("application/kate"),
    APPLICATION_OGG("application/ogg"),
    AUDIO_X_OGGPCM("audio/x-oggpcm"),
    VIDEO_X_OGGYUV("video/x-oggyuv"),
    VIDEO_X_DIRAC("video/x-dirac"),
    VIDEO_X_OGM("video/x-ogm"),
    AUDIO_OGG("audio/ogg"),
    VIDEO_X_OGGUVS("video/x-ogguvs"),
    VIDEO_THEORA("video/theora"),
    VIDEO_X_OGGRGB("video/x-oggrgb"),
    VIDEO_OGG("video/ogg"),
    AUDIO_OPUS("audio/opus"),
    AUDIO_OGG_CODECS_OPUS("audio/ogg; codecs=opus"),
    AUDIO_SPEEX("audio/speex"),
    AUDIO_OGG_CODECS_SPEEX("audio/ogg; codecs=speex"),
    AUDIO_VORBIS("audio/vorbis");
       
    private final String value;
    
    private SupportedRegularMimeType(String value){
        this.value = value;
    }

    public String value() {
        return value;
    }
}
